version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install dependencies and build
          command: |
            cd ./app
            npm install
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./app/build

  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            cd ./app
            npm install
            npm run test

  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Sync build to S3
          command: |
            aws s3 sync ./app/build s3://ci-cd-example --delete
      - run:
          name: Invalidate CloudFront cache
          command: |
            aws cloudfront create-invalidation \
              --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
              --paths "/*"

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
